- name: Configure DNS
  hosts: all
  become: true
  tasks:
    - name: Stop and disable systemd-resolved
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Remove existing resolv.conf
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Create new resolv.conf
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          options timeout:2 attempts:3 rotate single-request-reopen

    - name: Apply netplan
      command: netplan apply
      ignore_errors: true
