- name: Install Kubernetes Components
  hosts: all
  become: true
  vars:
    kubernetes_version: "1.30.0-1.1"
  tasks:
    - name: Add Kubernetes GPG key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
        state: present
        filename: kubernetes

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet={{ kubernetes_version }}
          - kubectl={{ kubernetes_version }}
          - kubeadm={{ kubernetes_version }}
        state: present
        update_cache: yes

    - name: Hold kubelet, kubeadm, kubectl packages
      command: apt-mark hold {{ item }}
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Get host-only interface IP
      command: ip -o -4 addr list enp0s8
      register: enp0s8_ip

    - name: Set kubelet extra args
      copy:
        dest: /etc/default/kubelet
        content: "KUBELET_EXTRA_ARGS=--node-ip={{ enp0s8_ip.stdout_lines[0].split()[3].split('/')[0] }}"

    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted
