- name: Configure Netplan
  hosts: all
  become: true
  vars:
    netplan_config: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          enp0s3:
            dhcp4: yes
            dhcp4-overrides:
              use-dns: false
              use-routes: true
            dhcp6-overrides:
              use-dns: false
            optional: true
            nameservers:
              addresses:
                - 8.8.8.8
          enp0s8:
            dhcp4: no
            addresses:
              - 192.168.56.10/24
            routes:
              - to: 192.168.56.0/24
                via: 192.168.56.1
            nameservers: {}
  tasks:
    - name: Write netplan configuration
      copy:
        dest: /etc/netplan/01-netcfg.yaml
        content: "{{ netplan_config }}"
        mode: '0600'

    - name: Apply netplan
      command: netplan apply
