---
- name: Configure Netplan networking
  hosts: all
  become: yes
  tasks:
    - name: Create netplan configuration file
      copy:
        dest: /etc/netplan/01-netcfg.yaml
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              enp0s3: # NAT interface
                dhcp4: yes
                dhcp4-overrides:
                  use-dns: false
                  use-routes: true
                dhcp6-overrides:
                  use-dns: false
                optional: true
                nameservers:
                  addresses:
                    - 8.8.8.8
                    - 1.1.1.1
              enp0s8: # Host-only interface
                dhcp4: no
                addresses:
                  - 192.168.56.10/24
                routes:
                  - to: 192.168.56.0/24
                    via: 192.168.56.1
                nameservers:
                  addresses:
                    - 8.8.8.8
                    - 1.1.1.1

    - name: Fix permissions for netplan files
      file:
        path: /etc/netplan/01-netcfg.yaml
        owner: root
        group: root
        mode: '0600'

    - name: Apply netplan configuration
      command: netplan apply
