apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: cicd
data:
  plugins.txt: |
    kubernetes:latest
    workflow-aggregator:latest
    git:latest
    configuration-as-code:latest
    docker-workflow:latest
    blueocean:latest
    sonar:latest
    trivy:latest
    gitleaks:latest
    ssh-slaves:latest
    matrix-auth:latest
    credentials-binding:latest
    pipeline-github-lib:latest
    job-dsl:latest
    cloudbees-folder:latest
  jenkins.yaml: |
    jenkins:
      systemMessage: "Jenkins configured using JCasC"
      securityRealm:
        local:
          allowsSignup: false
          users:
          - id: "admin"
            password: "admin"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
