apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: cicd
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/jenkins"
  claimRef:
    namespace: cicd
    name: jenkins-pvc
