---
- name: Setup Kubernetes environment on VMs
  hosts: vm
  become: yes
  gather_facts: yes

  tasks:
    - name: Run netplan configuration
      import_playbook: netplan-config.yml

    - name: Run DNS configuration
      import_playbook: dns-config.yml

    - name: Install containerd runtime
      import_playbook: install-containerd.yml

    - name: Prepare kubernetes node prerequisites
      import_playbook: prepare-kube.yml  

    - name: Install Kubernetes components
      import_playbook: install-kube.yml

    - name: Prepare Kubernetes cluster
      import_playbook: prepare-kube.yml
