apiVersion: batch/v1
kind: Job
metadata:
  name: debug-kaniko
  namespace: build
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never

      initContainers:
        - name: git-clone
          image: alpine/git
          env:
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: git-credentials
                  key: username
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: git-credentials
                  key: password
          command:
            - sh
            - -c
            - |
              git clone https://$GIT_USERNAME:$GIT_PASSWORD@github.com/zakaria-statistics/infra-test.git /workspace
          volumeMounts:
            - name: build-context
              mountPath: /workspace
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          env:
            - name: BUILD_CONTEXT
              valueFrom:
                configMapKeyRef:
                  name: kaniko-build-config
                  key: context
            - name: DOCKERFILE
              valueFrom:
                configMapKeyRef:
                  name: kaniko-build-config
                  key: dockerfile
            - name: DESTINATION
              valueFrom:
                configMapKeyRef:
                  name: kaniko-build-config
                  key: destination
          args:
            - "--context=$(BUILD_CONTEXT)"
            - "--dockerfile=$(DOCKERFILE)"
            - "--destination=$(DESTINATION)"
            - "--cache=true"
            - "--cache-repo=docker.io/zacklordbing1909/test-cache"
          volumeMounts:
            - name: kaniko-secret
              mountPath: /kaniko/.docker
            - name: build-context
              mountPath: /workspace
          resources:
            requests:
              cpu: "1000m"
              memory: "1024Mi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"

      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: build-context
          emptyDir: {}
