apiVersion: v1
kind: ConfigMap
metadata:
  name: kaniko-build-config
  namespace: cicd
data:
  context: "git://github.com/zakaria-statistics/infra-test.git#refs/heads/main"
  dockerfile: "Dockerfile"
  destination: "docker.io/zacklordbing1909/test:latest"