apiVersion: v1
kind: ConfigMap
metadata:
  name: kaniko-build-config
  namespace: build
data:
  context: "/workspace"
  dockerfile: "Dockerfile"
  destination: "docker.io/zacklordbing1909/test:latest"
